# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - pipe: atlassian/sftp-deploy:0.5.5
            variables:
              USER: 'ec2-user'
              SERVER: '127.0.0.1'
              REMOTE_PATH: '/var/www/build/'
              LOCAL_PATH: 'build/*'
              SSH_KEY: $MY_SSH_KEY
              DEBUG: 'true'
              EXTRA_ARGS: '-o ServerAliveInterval=10'

